services:
  mysql:
    container_name: demo-mysql
    image: mysql:8.0.40
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./init-mysql.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - laravel

  laravel-app:
    container_name: laravel-app
    image: titouanlfrt/eval-devops:latest
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - laravel



networks:
      laravel:
        name: laravel-network
        driver: bridge
