name: Laravel

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.4'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer update && composer install --prefer-dist --no-progress --no-suggest --no-interaction
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: setup .env
      run: |
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: php artisan test

    - name: cree artefact
      uses: actions/upload-artifact@v4
      with:
        name: laravel-app
        path: .


  docker:
    name: build & push docker image
    runs-on: ubuntu-latest
    needs: laravel-tests
    steps:
      - name: checkout repo
        uses: actions/checkout@v5
      - name: download laravel artefact
        uses: actions/download-artifact@v4
        with:
          name: laravel-app
          path: ./app
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: docker build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eval-devops:latest
    
  runner:
    name: run docker containers
    runs-on: self-hosted
    needs: docker
    steps:
      - name: checkout repo
        uses: actions/checkout@v5
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2
      - name: Run Docker Compose
        run: docker compose up -d --pull always --force-recreate --no-deps laravel-app